# Generated by Django 6.0 on 2026-01-07 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='antecedents',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='notes_medecin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact_urgence',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_familiaux',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_personnels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medecin_traitant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='observations_administratives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_patient',
            field=models.CharField(default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DocumentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ORDONNANCE', 'Ordonnance'), ('CERTIFICAT', 'Certificat médical'), ('COMPTE_RENDU', 'Compte rendu'), ('DOCUMENT', 'Document scanné')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents_medicaux/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.dossiermedical')),
            ],
        ),
    ]
