# Generated by Django 6.0 on 2026-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_dossiermedical_antecedents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='numero_assure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_securite_sociale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='organisme_assurance',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_assurance',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente')], default='en_attente', max_length=20),
        ),
    ]
