# Generated by Django 6.0 on 2026-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_numero_assure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='certificats_medicaux',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='chirurgies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='commentaires_specialistes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='comptes_rendus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_dernier_examen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_diagnostic',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='documents_scannes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examens_biologiques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examens_radiologiques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='frequence_cardiaque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='historique_medical',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='hospitalisations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='intolerances',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='maladies_actuelles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='notes_medecin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='observance_traitement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='ordonnances_archivees',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='plan_suivi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='rappels_vaccinaux',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='reaction_allergique_grave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='resultats_laboratoire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='risques_particuliers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='statut_chronique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='taille',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='tension_arterielle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='traitements_anterieurs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='traitements_en_cours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='vaccinations',
            field=models.TextField(blank=True),
        ),
    ]
